name: Streaming Metadata CI

on: push
#   schedule:
#   - cron: '0 0 * * SUN'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: |
        npm install
    - name: Compile
      run: |
        npm run build
    - name: Test
      if: success()
      run: |
        npm test && npm pack
      env:
        CI: true
    # - name: Publish Coverage
    #   uses: codecov/codecov-action@v1
    #   if: success()
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
